### PR TITLE
Fix tooltip in schedule creation sidebar

### LINKED ISSUE #887: Meeting details => Video Link pop-up help text is truncated
Steps to reproduce:

- Browse to the Appointment dashboard
- On the right side click on and expand the `Meeting details` panel
- Move the mouse to over top of the ? beside the `Video Link` text to force the help text to appear
- Notice the help text is truncated on the left side

Image

### PR DESCRIPTION
**Pull request by devmount**
## Description of the Change

This PR fixes an issue, where overflowing contents in the schedule creation sidebar were hidden behind adjacent elements. This happened because of reversed overlapping priority due to reversed flex items and got fixed by setting a z-index.

image

This also fixes another linter warning in App.vue.

## Benefits

Overlapping should show again.

## Applicable Issues

Closes #887

### CODE REVIEW

File: frontend/src/App.vue [hunk 1]
```diff
@@ -165,7 +164,7 @@ const onPageLoad = async () => {
     resolution: deviceRes,
     effective_resolution: effectiveDeviceRes,
     user_agent: navigator.userAgent,
-    locale: defaultLocale(),
+    locale: defaultLocale(), // needs to import defaultLocale from utils
```
Comment (rwood-moz) [inline frontend/src/App.vue:167]: I'm a bit confused by how this still works when the `import defaultLocale` has been removed and is required as noted by the comment.

**Review by rwood-moz — APPROVED** [review]
Pulled branch locally and the tool tip now looks great, thanks! One question inline, just my own confusion...

File: frontend/src/App.vue (hunk 1 above)
Comment (devmount) [reply frontend/src/App.vue:167]: Haha well, that whole part is commented out. Which is why the linter is complaining in the first place. We had unused imports because of this commented out code. I removed the imports now and left a comment inside the commented area to import it again should we need that code in the future. We should ask @MelissaAutumn if we could delete that commented code altogether.

Sorry for the confusion 😅

**Review by MelissaAutumn — APPROVED** [review]
🎉

File: frontend/src/App.vue (hunk 1 above)
Comment (rwood-moz) [reply frontend/src/App.vue:167]: Ahhh hahhaha my bad I didn't even notice that entire section was commented out. Thanks 😃
