### PR TITLE
Fix overlapping hold events and auto confirm setting

### LINKED ISSUE #1246: Overlapping Hold / Non-Hold events in calendar
**Describe the bug**
When the user's Availability setting is to auto-confirm appointments, there are overlapping / duplicated hold and non-hold events on the calendar. This shouldn't be the case as the 'Hold' event was not even supposed to be there in the first place if it is auto-confirm.

Ref https://github.com/thunderbird/appointment/pull/1235#pullrequestreview-3207620764

**To Reproduce**

1. Go to Availability and make sure to set `Automatically confirm bookings if time is available` to true / checked
2. Book and appointment and take note of when this is taking place
3. Go to Dashboard and check that there are two events for the same appointment overlapping with each other

**Expected behavior**
The HOLD event should not be created

**Actual behavior**
HOLD event is created an overlaps with the non-HOLD event

**Screenshots**
image

### PR DESCRIPTION
**Pull request by devmount**
## Description of the Change

This change fixes two issues:

1. Availability page: The auto confirm setting (a toggle with the label "Automatically confirm bookings if time is available") now stores the correct boolean in to the database
2. Dashboard page: The week calendar now won't show remote events anymore, if there is a pending appointment placeholder at the same time and with the same title.

image

## Benefits

Pending event functionality should work and show up as expected again.

## Applicable Issues

Closes #1246

### CODE REVIEW

File: frontend/src/views/AvailabilityView/components/AvailabilitySettings/index.vue [hunk 1]
```diff
@@ -116,10 +118,10 @@ export default {
 
       <!-- Automatically confirm booking checkbox -->
       <checkbox-input
-        :name="t('label.automaticallyConfirmBookingsIfTimeIsAvailable')"
+        name="availability-automatically-confirm"
```
Comment (devmount) [inline frontend/src/views/AvailabilityView/components/AvailabilitySettings/index.vue:121]: The label wasn't really suitable as input name here 😇

File: frontend/src/views/AvailabilityView/components/AvailabilitySettings/index.vue [hunk 2]
```diff
@@ -30,10 +30,12 @@ const isBookable = computed({
   }
 })
 
-const requiresBookingConfirmation = computed({
-  get: () => currentState.value.booking_confirmation,
+// The database stores a boolean, if booking requests should have manual confirmation. However, since we offer 
+// an "automatic confirmation" toggle in the UI, we need to negate the value from the database here.
+const autoConfirmBookings = computed({
```
Comment (devmount) [inline frontend/src/views/AvailabilityView/components/AvailabilitySettings/index.vue:35]: I commented and renamed that computed prop for a less confusing name

File: frontend/src/views/DashboardView/components/WeekCalendar.vue [hunk 3]
```diff
@@ -312,6 +286,37 @@ const filteredPendingAppointmentsForGrid = computed(() => {
...
+  const remoteEventsWithinActiveWeek = props.events.filter((remoteEvent) => dj(remoteEvent.start).isBetween(start, end))
+
+  return remoteEventsWithinActiveWeek.map(remoteEvent => {
+    const eventStart = dj(remoteEvent.start);
+    const eventEnd = dj(remoteEvent.end);
+
+    const gridPosition = calculateEventGridPosition(eventStart, eventEnd, slots);
+    const hasPendingPlaceholder = filteredPendingAppointmentsForGrid.value.find(
+      (a) => a.title === remoteEvent.title && eventStart.isSame(a.start)
+    );
```
Comment (devmount) [inline frontend/src/views/DashboardView/components/WeekCalendar.vue:307]: I just added this condition and therefore moved the whole computed prop beneath the filteredPendingAppointmentsForGrid

**Review by rwood-moz — COMMENTED** [review]
LGTM and looks like it works fine for me locally, although I will leave it to @davinotdavid to approve since he filed the original issue that this PR fixes.

**Review by davinotdavid — APPROVED** [review]
@devmount Thanks for working on this! LGTM 🎉
