### PR TITLE
Remove unused typescript code

### LINKED ISSUE #1609: Remove unused frontend code
**Describe the bug**
Throughout the years and several redesigns, the frontend codebase has a few functions, Vue-provide statements or exports, that are defined but not used anymore and should be removed.

**Findings**
The following (wip) list contains potentially removable code snippets.

> [!NOTE]
> The lines listed are only the definition. The actual number of lines that can be deleted is bigger in most cases.

- https://github.com/thunderbird/appointment/blob/6965d857b107bd495df9329e448e4028e3cb7de8/frontend/src/utils.ts#L104
- https://github.com/thunderbird/appointment/blob/6965d857b107bd495df9329e448e4028e3cb7de8/frontend/src/keys.ts#L22
- https://github.com/thunderbird/appointment/blob/6965d857b107bd495df9329e448e4028e3cb7de8/frontend/src/keys.ts#L26
- https://github.com/thunderbird/appointment/blob/6965d857b107bd495df9329e448e4028e3cb7de8/frontend/src/definitions.ts#L39
- https://github.com/thunderbird/appointment/blob/6965d857b107bd495df9329e448e4028e3cb7de8/frontend/src/definitions.ts#L84
- https://github.com/thunderbird/appointment/blob/6965d857b107bd495df9329e448e4028e3cb7de8/frontend/src/definitions.ts#L94
- https://github.com/thunderbird/appointment/blob/6965d857b107bd495df9329e448e4028e3cb7de8/frontend/src/definitions.ts#L105
- https://github.com/thunderbird/appointment/blob/6965d857b107bd495df9329e448e4028e3cb7de8/frontend/src/definitions.ts#L118
- https://github.com/thunderbird/appointment/blob/6965d857b107bd495df9329e448e4028e3cb7de8/frontend/src/definitions.ts#L182
- https://github.com/thunderbird/appointment/blob/6965d857b107bd495df9329e448e4028e3cb7de8/frontend/src/definitions.ts#L250
- https://github.com/thunderbird/appointment/blob/6965d857b107bd495df9329e448e4028e3cb7de8/frontend/src/models.ts#L377
- https://github.com/thunderbird/appointment/blob/6965d857b107bd495df9329e448e4028e3cb7de8/frontend/src/models.ts#L388

**Additional context**
I found those when implementing another feature. So we can just keep an eye open for dead code and throw possible findings in here until we purge the list.

### PR DESCRIPTION
**Pull request by devmount**
## What changed?

This is a maintenance change and contains code removal only. No functionality was changed.

## Why?

Lighter frontend code base.

## Limitations and Notes

I focused on unused exports and provides at root level. There might be more unused code in specific components.

## Applicable Issues

Closes #1609

### CODE REVIEW

File: frontend/src/App.vue [hunk 1]
```diff
@@ -50,8 +45,6 @@ const {
   lock: lockNotification,
 } = siteNotificationStore;
 
-provide(accountsTbProfileUrlKey, import.meta.env.VITE_TB_ACCOUNT_DASHBOARD_URL);
```
Comment (davinotdavid) [inline frontend/src/App.vue:53]: I think we should instead have the users of `VITE_TB_ACCOUNT_DASHBOARD_URL` use the inject / key so that in the odd case that its content changes, we don't have to change in all places.

For example:

https://github.com/thunderbird/appointment/blob/add-zoom-link-to-confirmation-email/frontend/src/components/UserMenu.vue#L11-L12

We can punt this to another ticket though!

(Also `VITE_SUPPORT_URL` is being used a lot more throughout the codebase so we should probably punt it into a provide / inject key as well)

**Review by davinotdavid — APPROVED** [review]
lgtm, thanks for the cleanup! one comment:

File: frontend/src/App.vue (hunk 1 above)
Comment (devmount) [reply frontend/src/App.vue:53]: Great suggestion, thanks so much! I added provides/injects directly for the following constants now:

- `VITE_TB_ACCOUNT_DASHBOARD_URL`
- `VITE_TB_PRO_URL`
- `VITE_SUPPORT_URL`

Comment (davinotdavid) [reply frontend/src/App.vue:53]: Neat, thanks!

**Review by davinotdavid — APPROVED** [review]
Thanks!
