### PR TITLE
Disable deactivation of default calendar and sync availability

### LINKED ISSUE #1333: Default calendar toggle should be disabled
**Describe the bug**
The current UI allows the default calendar (the one used for the active schedule) to be deactivated. This shouldn't be possible according to designs.

**To Reproduce**

1. Go to Settings > Connected applications
2. Remove the tick on the default calendar
3. Save
4. Reload / revisit page to see that the changes were actually saved

**Expected behavior**
The default calendar is grayed out, so that it cannot be disabled, unless another calendar is set in the availability settings before.

**Actual behavior**
The default calendar can be disabled. This leads to an empty calendar select field in the availability settings. And even worse: When reloading the availability page, the next available calendar is displayed (but not actually used).

**Screenshots**
Design:

Image

Current implementation:

Image

**System (please complete the following information):**

- OS: Tuxedo OS (Ubuntu 24)
- Thunderbird Version 140.4.0esr (64-Bit)

**Additional context**
This might be related to #1311 as well.

### PR DESCRIPTION
**Pull request by devmount**
## Description of the Change

This change fixes a UI issue, where the default calendar can be disabled in the calendar settings. Also the default calendar changed in the settings is now properly synced to the availability page too (this was only the case the other way around until now).

## Benefits

Prevention of faulty availability/calnedar behaviour. Reduction of user confusion.

## Applicable Issues

Closes #1333 and hopefully #1311

### CODE REVIEW

File: frontend/src/views/SettingsView/components/ConnectedApplications.vue [hunk 1]
```diff
@@ -57,6 +59,7 @@ const initialCalendars = computed(() => {
       type_id: externalConnection?.type_id,
       connection_name: externalConnection?.name,
       provider_name: connectionProvider,
+      is_default: currentState.value.defaultCalendarId === calendar.id,
```
Comment (devmount) [inline frontend/src/views/SettingsView/components/ConnectedApplications.vue:62]: This improves the markup a lot, because we now already have that information as property

File: frontend/src/views/SettingsView/components/ConnectedApplications.vue [hunk 2]
```diff
@@ -129,7 +132,13 @@ function onCalendarChecked(event: HTMLInputElementEvent, calendarId: number) {
...
   // Only update local state, the actual schedule's calendar change
   // happens on save changes in SettingsView/index.vue
-  settingsStore.$patch({ currentState: { defaultCalendarId: calendarId }})
+  settingsStore.$patch({ currentState: { defaultCalendarId: calendarId }});
+  // Update the current availability too, otherwise it will be out
+  // of sync until the user refreshes the page
+  availabilityStore.$patch({
+    initialState: { calendar_id: calendarId },
+    currentState: { calendar_id: calendarId },
+  });
```
Comment (devmount) [inline frontend/src/views/SettingsView/components/ConnectedApplications.vue:141]: This fixes the out of sync availability config page, when changing calendars in the settings. We need to update both states, otherwise the availability page will find a mismatch and offer to save changes.

**Comment by rwood-moz** [comment]
Ooops I added my review comment to the issue instead, sorry:

https://github.com/thunderbird/appointment/issues/1333#issuecomment-3528377784

**Comment by devmount** [comment]
Thanks both of you,  @rwood-moz and @davinotdavid!! I fixed the row alignment now and the drop down now only shows up, if at least one active button exists:

image

**Comment by rwood-moz** [comment]
Thanks @devmount! The menu now is not available for the default calendar (awesome) but now unfortunately there are some issues with the alignment of the other calendars that appear below the default one:

Screenshot 2025-11-13 at 4 47 26 PM

**Comment by devmount** [comment]
> Thanks @devmount! The menu now is not available for the default calendar (awesome) but now unfortunately there are some issues with the alignment of the other calendars that appear below the default one:

Oh hahaha, I just love CSS grids 😂  Thanks so much for catching this, Rob! Should be fixed now
